"""initial schema

Revision ID: 76c2a1d4aeb7
Revises: 
Create Date: 2026-02-25 23:44:02.574409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76c2a1d4aeb7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('is_fiat', sa.Boolean(), nullable=False),
    sa.Column('coingecko_id', sa.String(length=255), nullable=True),
    sa.Column('decimals', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('blockchain', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('koinly_wallet_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('import_type', sa.String(length=50), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('transactions_imported', sa.Integer(), nullable=False),
    sa.Column('transactions_skipped', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price_usd', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'date', 'source', name='uq_price_asset_date_source')
    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index('idx_price_history_lookup', ['asset_id', 'date'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('koinly_tx_id', sa.String(length=255), nullable=True),
    sa.Column('tx_hash', sa.String(length=255), nullable=True),
    sa.Column('datetime_utc', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('from_wallet_id', sa.Integer(), nullable=True),
    sa.Column('to_wallet_id', sa.Integer(), nullable=True),
    sa.Column('from_amount', sa.String(length=60), nullable=True),
    sa.Column('from_asset_id', sa.Integer(), nullable=True),
    sa.Column('to_amount', sa.String(length=60), nullable=True),
    sa.Column('to_asset_id', sa.Integer(), nullable=True),
    sa.Column('fee_amount', sa.String(length=60), nullable=True),
    sa.Column('fee_asset_id', sa.Integer(), nullable=True),
    sa.Column('fee_value_usd', sa.String(length=30), nullable=True),
    sa.Column('from_value_usd', sa.String(length=30), nullable=True),
    sa.Column('to_value_usd', sa.String(length=30), nullable=True),
    sa.Column('net_value_usd', sa.String(length=30), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_margin', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('reported_on_1099da', sa.Boolean(), nullable=False),
    sa.Column('basis_reported_to_irs', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fee_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['from_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['from_wallet_id'], ['wallets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['to_wallet_id'], ['wallets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('koinly_tx_id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('idx_transactions_datetime', ['datetime_utc'], unique=False)
        batch_op.create_index('idx_transactions_koinly_id', ['koinly_tx_id'], unique=False)
        batch_op.create_index('idx_transactions_to_wallet_asset', ['to_wallet_id', 'to_asset_id'], unique=False)
        batch_op.create_index('idx_transactions_tx_hash', ['tx_hash'], unique=False)
        batch_op.create_index('idx_transactions_type', ['type'], unique=False)
        batch_op.create_index('idx_transactions_wallet_asset', ['from_wallet_id', 'from_asset_id'], unique=False)

    op.create_table('wallet_cost_basis_methods',
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('cost_basis_method', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('wallet_id', 'tax_year')
    )
    op.create_table('tax_lots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.String(length=60), nullable=False),
    sa.Column('remaining_amount', sa.String(length=60), nullable=False),
    sa.Column('cost_basis_usd', sa.String(length=30), nullable=False),
    sa.Column('cost_basis_per_unit', sa.String(length=30), nullable=False),
    sa.Column('acquired_date', sa.DateTime(), nullable=False),
    sa.Column('acquisition_tx_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('is_fully_disposed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['acquisition_tx_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_lots', schema=None) as batch_op:
        batch_op.create_index('idx_tax_lots_remaining', ['wallet_id', 'asset_id', 'is_fully_disposed'], unique=False)
        batch_op.create_index('idx_tax_lots_wallet_asset', ['wallet_id', 'asset_id'], unique=False)

    op.create_table('lot_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('disposal_tx_id', sa.Integer(), nullable=False),
    sa.Column('tax_lot_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.String(length=60), nullable=False),
    sa.Column('cost_basis_usd', sa.String(length=30), nullable=False),
    sa.Column('proceeds_usd', sa.String(length=30), nullable=False),
    sa.Column('gain_loss_usd', sa.String(length=30), nullable=False),
    sa.Column('holding_period', sa.String(length=20), nullable=False),
    sa.Column('cost_basis_method', sa.String(length=20), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['disposal_tx_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tax_lot_id'], ['tax_lots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lot_assignments', schema=None) as batch_op:
        batch_op.create_index('idx_lot_assignments_disposal', ['disposal_tx_id'], unique=False)
        batch_op.create_index('idx_lot_assignments_lot', ['tax_lot_id'], unique=False)
        batch_op.create_index('idx_lot_assignments_year', ['tax_year'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lot_assignments', schema=None) as batch_op:
        batch_op.drop_index('idx_lot_assignments_year')
        batch_op.drop_index('idx_lot_assignments_lot')
        batch_op.drop_index('idx_lot_assignments_disposal')

    op.drop_table('lot_assignments')
    with op.batch_alter_table('tax_lots', schema=None) as batch_op:
        batch_op.drop_index('idx_tax_lots_wallet_asset')
        batch_op.drop_index('idx_tax_lots_remaining')

    op.drop_table('tax_lots')
    op.drop_table('wallet_cost_basis_methods')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('idx_transactions_wallet_asset')
        batch_op.drop_index('idx_transactions_type')
        batch_op.drop_index('idx_transactions_tx_hash')
        batch_op.drop_index('idx_transactions_to_wallet_asset')
        batch_op.drop_index('idx_transactions_koinly_id')
        batch_op.drop_index('idx_transactions_datetime')

    op.drop_table('transactions')
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index('idx_price_history_lookup')

    op.drop_table('price_history')
    op.drop_table('import_logs')
    op.drop_table('wallets')
    op.drop_table('settings')
    op.drop_table('assets')
    # ### end Alembic commands ###
